### ISSUE TITLE
[Feature Request] Use URL to inform initial app state

### ISSUE THREAD

**Issue by charmsRace** [farnots/RedditToMarkdown#1]
e.g. `https://farnots.github.io/RedditToMarkdown/https://www.reddit.com/r/ObsidianMD/comments/p2tioh/save_reddit_posts_to_obsidian/`

would be linked to the page you see after you type `https://www.reddit.com/r/ObsidianMD/comments/p2tioh/save_reddit_posts_to_obsidian/` in the RedditToMarkdown URL field.

If this were possible, you could do something like, Google Chrome + Firefox support a "custom search engine" thing in the URL bar where you can set hotwords to search specific websites, it works by giving it a template containing `%s` which is your search term, e.g. `https://www.reddit.com/r/ObsidianMD/search/?q=%s`. So you could do `https://farnots.github.io/RedditToMarkdown/%s` and then in the browser URL bar you could type `redobs https://www.reddit.com/r/ObsidianMD/comments/p2tioh/save_reddit_posts_to_obsidian/` to go to that state of the RedditToMarkdown app.

I know this project is 5 years old but I thought I'd put the idea on the table 😊

**Comment by farnots** [comment]
Resolve by `https://github.com/farnots/RedditToMarkdown/pull/2`
